import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Centre Of Metaverse",
  description: "Generated by create next app",
};

const futuraMaxiBold = localFont({
  src: "./fonts/futuramaxicgboldopentype.woff",
  display: "swap",
  variable: "--font-futura-maxi-bold",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${futuraMaxiBold.variable}`}>
        {children}
      </body>
    </html>
  );
}
